# Generated by Django 4.2 on 2023-05-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='watchlists',
        ),
        migrations.AddField(
            model_name='review',
            name='is_critic_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='is_critic',
            field=models.BooleanField(default=False),
        ),
    ]
